version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: elms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: elmsdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: elms-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/elmsdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

volumes:
  mysql_data: